=== alonsocj/parcial1_grupo05/Parte03/registrofacturasgrupo05.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--registrofacturasgrupo05.xsd grupo 05-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
  
  <xs:element name="registro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="responsable" type="format_resp"/>
        
        <xs:element name="factura" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="num" type="format_num"/>
              
              <xs:element name="cliente">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombre" type="format_name"/>
                    
                    <!--III.1.4-->
                    <xs:element name="documento">
                      <xs:complexType>
                        <xs:choice minOccurs="0" maxOccurs="1"> <!--Cambio de secuence a choice-->
                        
                        <!--Elementos-->
                          <xs:element name="dui">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="format_dui">
                                  <xs:attribute name="vence" type="format_vencimiento" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>

                          <xs:element name="pasaporte">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="format_pasaport">
                                  <xs:attribute name="pais" type="format_pais" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>

                        </xs:choice>
                      </xs:complexType>
                    </xs:element>


                    <xs:element name="telefono">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="format_telefono">
                            <xs:attribute name="tipo" type="format_tipotelefono" use="required"/>
                            <xs:attribute name="cia" type="format_cia" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>


                    <xs:element name="email" type="emailformat"/>
                  </xs:sequence>
                  <xs:attribute name="codigo" type="format_cod" use="required"/>
                  <xs:attribute name="sexo" type="format_gen" use="required"/>
                </xs:complexType>
              </xs:element>

              <!--III.1.4-->
              <xs:element name="direccion" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:choice minOccurs="0" maxOccurs="1"> <!--Cambio de secuence a choice-->
                    <xs:element name="casa" type="format_lugar"/>
                    <xs:element name="oficina" type="format_lugar"/>
                  </xs:choice>
                  <xs:attribute name="depto" type="format_depart" use="required"/>
                  <xs:attribute name="municipio" type="format_municipio" use="required"/>
                </xs:complexType>
              </xs:element>


              <xs:element name="lineafactura">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="codigo">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="codefacture">
                            <xs:attribute name="tipo" type="format_codLinfacture" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="detalle" type="format_detalle"/>
                    <xs:element name="cantidad" type="format_cantidad"/>
                    <xs:element name="precio">
                      <xs:complexType>
                        <xs:sequence>
                          <!--III.1.9 Uso de referencia-->
                          <xs:group ref="grupo_ingresos"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="subtotal">
                      <xs:complexType>
                        <xs:sequence>
                        <!--III.1.9 Uso de referencia-->
                          <xs:group ref="grupo_ingresos"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="factura" type="codelineafacture" use="required"/>
                </xs:complexType>
              </xs:element>

              <xs:element name="total">
                <xs:complexType>
                  <xs:sequence>
                  <!--III.1.9 Uso de referencia-->
                    <xs:group ref="grupo_ingresos"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="tipo" type="format_factura" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="periodo" type="format_periodo" use="required"/>
    </xs:complexType>
  </xs:element>
  
<!-- Reutilizacion de elementos -->

<!--He definido una sola estructura para que podamos modificarlo de acuerdo a reutilización y
evitar la escritura masiva de codigo y hacer buenas practicas de programación -->

<!--III.1.1-->
<!--Para atributo-->
<xs:simpleType name="format_cia">
  <xs:restriction base="xs:string">
    <xs:enumeration value="tigo"/>
    <xs:enumeration value="digicel"/>
    <xs:enumeration value="claro"/>
    <xs:enumeration value="movistar"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="format_tipotelefono">
  <xs:restriction base="xs:string">
    <xs:enumeration value="celular"/>
    <xs:enumeration value="fijo"/>
    <xs:enumeration value="fax"/>
  </xs:restriction>
</xs:simpleType>

<!--III.1.1-->
<!--Codigo de linea factura, Su atributo-->
<xs:simpleType name="format_codLinfacture">
  <xs:restriction base="xs:string">
    <xs:enumeration value="souvenir"/>
    <xs:enumeration value="pcportatiles"/>
    <xs:enumeration value="accesorio_pc"/>
    <xs:enumeration value="perecedero"/>
  </xs:restriction>
</xs:simpleType>

<!--III.1.3-->
<xs:simpleType name="emailformat">
<xs:restriction base="xs:string">
<!--Utilizacion de una Expresion regular III.1.2-->
  <xs:pattern value="[a-z0-9A-Z]{5,12}@[a-z0-9A-Z]{3,10}[\.][a-zA-Z]{3,4}"/>
</xs:restriction>
</xs:simpleType>

<!--Definicion de grupo III.1.5-->
<xs:group name="grupo_ingresos">
  <xs:sequence>
     <xs:element name="moneda" type="format_coin"/>
     <xs:element name="valor" type="format_precio"/>
  </xs:sequence>
</xs:group>

<!--III.1.6-->

<!--Validacion cantidad-->
<xs:simpleType name="format_cantidad">
  <xs:restriction base="xs:double">
    <xs:minInclusive value="1"/>
  </xs:restriction>
</xs:simpleType>

<!--Fecha de vencimiento-->
<xs:simpleType name="format_vencimiento">
  <xs:restriction base="xs:date">
<!--Utilizacion de una Expresion regular III.1.2-->
  <xs:pattern value="[2][0]([0-2][0-1]|[0-1][0-9])[\-]((([0][1]|[0][3]|[0][5]|[0][7]|[0][8]|[1][0]|[1][2])[\-]([0][1-9]|[1-2][0-9]|[3][0-1]))|(([0][4]|[0][6]|[0][9]|[0][7]|[1][1])[\-]([0][1-9]|[1-2][0-9]|[3][0]))|(([0][2])[\-]([0][1-9]|[1-2][0-8])))"/>
  </xs:restriction>
</xs:simpleType>

<!--Definicion telefono-->
<xs:simpleType name="format_telefono">
  <xs:restriction base="xs:integer">
<!--Utilizacion de una Expresion regular III.1.2-->
  <xs:pattern value="[0-9]{8}"/>
  </xs:restriction>
</xs:simpleType>

<!--Definicion nombre, detalle, y direccion-->
<!--III.1.7 Utilización de reestricciones de longitud-->
<xs:simpleType name="format_name">
  <xs:restriction base="xs:string">
    <xs:minLength value="10"/>
    <xs:maxLength value="25"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="format_lugar">
  <xs:restriction base="xs:string">
    <xs:minLength value="7"/>
    <xs:maxLength value="40"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="format_detalle">
  <xs:restriction base="xs:string">
    <xs:minLength value="10"/>
    <xs:maxLength value="50"/>
  </xs:restriction>
</xs:simpleType>

<!--III.1.8-->
<xs:simpleType name="format_precio">
<xs:restriction base="xs:decimal">
  <xs:minInclusive value="0.01"/>
  <xs:maxInclusive value="9999.99"/>
  <xs:totalDigits value="6"/>
  <xs:fractionDigits value="2"/>
</xs:restriction>
</xs:simpleType>

<!--Otras validaciones del XML [Utilizando requerimientos solicitados] -->

<!--Validar codigo de linea de factura-->
<xs:simpleType name="codefacture">
  <xs:restriction base="xs:string">
<!--Utilizacion de una Expresion regular III.1.2-->
    <xs:pattern value="[0-9]{3}"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="codelineafacture">
  <xs:restriction base="xs:string">
<!--Utilizacion de una Expresion regular III.1.2-->
    <xs:pattern value="[0-9]{3}"/>
  </xs:restriction>
</xs:simpleType>

<!--Dui-->
<xs:simpleType name="format_dui">
  <xs:restriction base="xs:string">
<!--Utilizacion de una Expresion regular III.1.2-->
    <xs:pattern value="[0-9]{8}[\-][0-9]{1}"/>
  </xs:restriction>
</xs:simpleType>

<!--Pasaporte-->
<xs:simpleType name="format_pasaport">
  <xs:restriction base="xs:string">
<!--Utilizacion de una Expresion regular III.1.2-->
    <xs:pattern value="[A-Z]{1}[0-9]{8}"/>
  </xs:restriction>
</xs:simpleType>

<!--Pais pasaporte-->
<xs:simpleType name="format_pais">
  <xs:restriction base="xs:string">
<!--Utilizacion de una Expresion regular III.1.2-->
  <xs:pattern value="[A-Z]{3}"/>
  </xs:restriction>
</xs:simpleType>

<!--Num-->
<xs:simpleType name="format_num">
  <xs:restriction base="xs:unsignedShort">
<!--Utilizacion de una Expresion regular III.1.2-->
    <xs:pattern value="[0-9]{3}"/>
  </xs:restriction>
</xs:simpleType>

<!--Direccion atributos-->
<xs:simpleType name="format_depart">
  <xs:restriction base="xs:string">
    <xs:maxLength value="12"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="format_municipio">
  <xs:restriction base="xs:string">
    <xs:maxLength value="30"/>
  </xs:restriction>
</xs:simpleType>

<!--Cliente-->
<!--Validacion sexo-->
<xs:simpleType name="format_gen">
  <xs:restriction base="xs:string">
  <xs:pattern value="femenino|masculino"/>
  </xs:restriction>
</xs:simpleType>

<!--Validacion codigo-->
<xs:simpleType name="format_cod">
  <xs:restriction base="xs:unsignedShort">
  <xs:pattern value="[0-9]{3,4}"/>
  </xs:restriction>
</xs:simpleType>

<!--Factura-->
<xs:simpleType name="format_factura">
  <xs:restriction base="xs:string">
  <xs:pattern value="final|credito"/>
  </xs:restriction>
</xs:simpleType>

<!--Validacion moneda-->
<xs:simpleType name="format_coin">
  <xs:restriction base="xs:string">
    <xs:pattern value="[$]"/>
  </xs:restriction>
</xs:simpleType>

<!--Validacion responsable-->
<xs:simpleType name="format_resp">
  <xs:restriction base="xs:string">
    <xs:pattern value="([Lic]|[Ing]|[Msc]|[Inga])+([\.][ ][a-zA-Záéíóú]+[ ]+[a-zA-Záéíóú]+)"/>
  </xs:restriction>
</xs:simpleType>

<!--Periodo-->
<xs:simpleType name="format_periodo">
  <xs:restriction base="xs:gYearMonth">
    <xs:pattern value="[2][0]([0-2][0-1]|[0-1][0-9])[\-]([0][1-9]|[1][0-2])"/>
  </xs:restriction>
</xs:simpleType>

</xs:schema>

=== alonsocj/parcial1_grupo05/Parte03/registro_facturas_grupo05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Grupo 05  -->
<!--Enlazar archivo xsd-->
<registro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="registrofacturasgrupo05.xsd" periodo="2012-03">
    <responsable>Lic. Inocencio Pérez</responsable>

    <!--Factura 1 -->
    <factura tipo="final">
        <num>564</num>

        <cliente codigo="2617" sexo="femenino">
            <nombre>María Vélez</nombre>
            <documento>
                <dui vence="2018-03-03">02349867-9</dui>
            </documento>
            <telefono tipo="fijo">24356789</telefono>
            <email>mariav@gmail.com</email>
        </cliente>

        <direccion depto="San Salvador" municipio="San Salvador">
            <casa>Prados del Bosque Num.23</casa>
        </direccion>

        <lineafactura factura="564">
            <codigo tipo="souvenir">498</codigo>
            <detalle>Llavero estampas de mi pueblo: Izalco</detalle>
            <cantidad>10</cantidad>

            <precio>
                <moneda>$</moneda>
                <valor>1.13</valor>
            </precio>

            <subtotal>
                <moneda>$</moneda>
                <valor>11.30</valor>
            </subtotal>

        </lineafactura>

        <total>
            <moneda>$</moneda>
            <valor>11.30</valor>
        </total>
    </factura>

    <!--Factura 2 -->
    <factura tipo="credito">
        <num>570</num>
        <cliente codigo="5032" sexo="femenino">
            <nombre>Julia Pérez</nombre>
            <documento>
                <pasaporte pais="USA">A98672340</pasaporte> <!--Atributo simple-->
            </documento>
            <telefono tipo="celular" cia="tigo">78354926</telefono>
            <email>jperez@sica.com</email>
        </cliente>
        <direccion depto="La Libertad" municipio="Antiguo Cuscatlan">
            <oficina>5 Av. Sur</oficina>
        </direccion>
        <lineafactura factura="570">
            <codigo tipo="pcportatiles">734</codigo>
            <detalle>netbook acer a240</detalle>
            <cantidad>3</cantidad>
            <precio>
                <moneda>$</moneda>
                <valor>350.00</valor>
            </precio>
            <subtotal>
                <moneda>$</moneda>
                <valor>1050.00</valor>
            </subtotal>
        </lineafactura>
        <total>
            <moneda>$</moneda>
            <valor>1050.00</valor>
        </total>
    </factura>

    <!--factura 3-->
    <factura tipo="credito">
        <num>575</num>
        <cliente codigo="5327" sexo="masculino">
            <nombre>Jhon Smith</nombre>
            <documento>
                <pasaporte pais="USA">A98670234</pasaporte>
            </documento>
            <telefono tipo="celular" cia="tigo">78923546</telefono>
            <email>jsmith@usaid.com</email>
        </cliente>
        <direccion depto="La Libertad" municipio="Santa Tecla">
            <oficina>Final 25 Av. Norte</oficina>
        </direccion>
        <lineafactura factura="575">
            <codigo tipo="accesorio_pc">247</codigo>
            <detalle>Mouse inalámbrico</detalle>
            <cantidad>5</cantidad>
            <precio>
                <moneda>$</moneda>
                <valor>10.00</valor>
            </precio>
            <subtotal>
                <moneda>$</moneda>
                <valor>50.00</valor>
            </subtotal>
        </lineafactura>
        <total>
            <moneda>$</moneda>
            <valor>50.00</valor>
        </total>
    </factura>

    <!--factura 4 -->
    <factura tipo="final">
        <num>590</num>
        <cliente codigo="617" sexo="masculino">
            <nombre>Juan Pérez</nombre>
            <documento>
                <pasaporte pais="SLV">A40298367</pasaporte>
            </documento>
            <telefono tipo="celular" cia="claro">76023546</telefono>
            <email>jperez@gmail.com</email>
        </cliente>
        <lineafactura factura="590">
            <codigo tipo="perecedero">213</codigo>
            <detalle>Agua embotellada</detalle>
            <cantidad>10</cantidad>
            <precio>
                <moneda>$</moneda>
                <valor>0.50</valor>
            </precio>
            <subtotal>
                <moneda>$</moneda>
                <valor>5.00</valor>
            </subtotal>
        </lineafactura>
        <total>
            <moneda>$</moneda>
            <valor>5.00</valor>
        </total>
    </factura>

    <!--factura 5-->
    <factura tipo="final">
        <num>593</num>
        <cliente codigo="177" sexo="masculino">
            <nombre>Pedro Portillo</nombre>
            <documento>
                <pasaporte pais="SLV">A43698027</pasaporte>
            </documento>
            <telefono tipo="celular" cia="claro">76028642</telefono>
            <email>pportillo@hotmail.com</email>
        </cliente>
        <lineafactura factura="593">
            <codigo tipo="perecedero">215</codigo>
            <detalle>Soda enlatada</detalle>
            <cantidad>24</cantidad>
            <precio>
                <moneda>$</moneda>
                <valor>0.50</valor>
            </precio>
            <subtotal>
                <moneda>$</moneda>
                <valor>5.00</valor>
            </subtotal>
        </lineafactura>
        <total>
            <moneda>$</moneda>
            <valor>5.00</valor>
        </total>
    </factura>

    <!--factura 6 -->
    <factura tipo="credito">
        <num>585</num>
        <cliente codigo="5327" sexo="masculino">
            <nombre>Jhon Smith</nombre>
            <documento>
                <dui vence="2018-06-03">02810867-0</dui>
            </documento>
            <telefono tipo="celular" cia="tigo">78923546</telefono>
            <email>jsmith@usaid.com</email>
        </cliente>
        <direccion depto="La Libertad" municipio="Santa Tecla">
            <oficina>Final 25 Av. Norte</oficina>
        </direccion>
        <lineafactura factura="575">
            <codigo tipo="accesorio_pc">247</codigo>
            <detalle>Mouse inalambrico</detalle>
            <cantidad>10</cantidad>
            <precio>
                <moneda>$</moneda>
                <valor>10.00</valor>
            </precio>
            <subtotal>
                <moneda>$</moneda>
                <valor>100.00</valor>
            </subtotal>
        </lineafactura>
        <total>
            <moneda>$</moneda>
            <valor>100.00</valor>
        </total>
    </factura>

    <!--Agregar las 4 facturas faltantes-->

    <!--factura 7 -->

    <factura tipo="final">
        <num>264</num>
        <cliente codigo="0867" sexo="masculino">
            <nombre>Julio Josè</nombre>
            <documento>
                <dui vence="2019-09-12">09870904-2</dui>
            </documento>
            <telefono tipo="celular" cia="claro">76982148</telefono>
            <email>juljos@gmail.com</email>
        </cliente>
        <direccion depto="La Libertad" municipio="Santa Tecla">
            <oficina>2a Av. Norte</oficina>
        </direccion>
        <lineafactura factura="139">
            <codigo tipo="perecedero">352</codigo>
            <detalle>Carne de res</detalle>
            <cantidad>2</cantidad>
            <precio>
                <moneda>$</moneda>
                <valor>4.15</valor>
            </precio>
            <subtotal>
                <moneda>$</moneda>
                <valor>8.30</valor>
            </subtotal>
        </lineafactura>
        <total>
            <moneda>$</moneda>
            <valor>8.30</valor>
        </total>
    </factura>


    <!--factura 8-->
    <factura tipo="final">
        <num>352</num>
        <cliente codigo="125" sexo="femenino">
            <nombre>Celeste Lopèz</nombre>
            <documento>
                <pasaporte pais="HND">C28792473</pasaporte>
            </documento>
            <telefono tipo="celular" cia="movistar">73209745</telefono>
            <email>cello@hotmail.com</email>
        </cliente>
        <lineafactura factura="209">
            <codigo tipo="accesorio_pc">654</codigo>
            <detalle>Teclado para PC</detalle>
            <cantidad>2</cantidad>
            <precio>
                <moneda>$</moneda>
                <valor>35.00</valor>
            </precio>
            <subtotal>
                <moneda>$</moneda>
                <valor>70.00</valor>
            </subtotal>
        </lineafactura>
        <total>
            <moneda>$</moneda>
            <valor>70.00</valor>
        </total>
    </factura>
    <!-- FACTURA 9-->
    <factura tipo="credito">
        <num>102</num>
        <cliente codigo="2753" sexo="femenino">
            <nombre>Monet Lott</nombre>
            <documento>
                <dui vence="2002-10-12">56457436-1</dui>
            </documento>
            <telefono tipo="celular">78952165</telefono>
            <email>mlott@email.com</email>
        </cliente>
        <direccion depto="Usulutan" municipio="Berlin">
            <oficina>Final 24 Av. Sur</oficina>
        </direccion>
        <lineafactura factura="650">
            <codigo tipo="accesorio_pc">580</codigo>
            <detalle>Procesador Ryzon</detalle>
            <cantidad>1</cantidad>
            <precio>
                <moneda>$</moneda>
                <valor>450</valor>
            </precio>
            <subtotal>
                <moneda>$</moneda>
                <valor>450</valor>
            </subtotal>
        </lineafactura>
        <total>
            <moneda>$</moneda>
            <valor>450</valor>
        </total>
    </factura>

    <!-- FACTURA 10-->

    <factura tipo="credito">
        <num>031</num>
        <cliente codigo="2156" sexo="masculino">
            <nombre>Adam Zapel</nombre>
            <documento>
                <dui vence="2012-11-25">65147852-5</dui>
            </documento>
            <telefono tipo="celular">66425485</telefono>
